### ISSUE TITLE
GetParameters API Fails if items exceeds 10

### ISSUE THREAD

**Issue by mithun** [remind101/ssm-env#10]
The [GetParameters API](http://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParameters.html#API_GetParameters_RequestSyntax) has a restriction of maximum 10 items.

Attempting to fetch more that 10 items fails with:

```shell
ssm-env: ValidationException: 1 validation error detected: Value '[list, of, ten, items]' at 'names' failed to satisfy constraint: Member must have length less than or equal to 10
```

**Comment by bsideup** [comment]
@ejholmes still not released :(

**Comment by ejholmes** [comment]
@bsideup @mithun sorry for the delay on this. There's now a [v0.0.3 release](https://github.com/remind101/ssm-env/releases/tag/v0.0.3) that includes this.
