### ISSUE TITLE
Proposed feature: Inject the environment into a bash invocation

### ISSUE THREAD

**Issue by r1b** [remind101/ssm-env#2]
I'm thinking of how the `watch` utility works:

```bash
watch 'ls -l'
```

The last parameter is a bash invocation - the output from that invocation is monitored.

It would be great if ssm-env ran a provided invocation in a child process and injected the environment from SSM into that process.

**Comment by ejholmes** [comment]
Hi @r1b. That's exactly how ssm-env works. The arguments that you provide after the `ssm-env` command is a command to `execve`. The environment variables in the command that's exec'd sees the plaintext values of the SSM parameters.

So, for example:, if you had a rails app, you might do something like this

```
$ export COOKIE_SECRET=ssm:///prod/cookie_secret
$ ssm-env rails server
```

The `COOKIE_SECRET` environment variable within the `rails server` command will be the value of the `/prod/cookie_secret` parameter.

The readme is probably a little confusing.

**Comment by r1b** [comment]
Oh! I thought `env` from the README was a file with variable assignments. Thank you for clarifying.
