### ISSUE TITLE
Incorrect checksum in Docker instructions

### ISSUE THREAD

**Issue by lazyguru** [remind101/ssm-env#23]
In the Docker instructions in the README (https://github.com/remind101/ssm-env#usage-with-docker) you reference ad0f184da3a6536d0614ce4133ceb23b as the checksum for v0.0.3, however that is the checksum for v0.0.2 so the check fails. da4bac1c1937da4689e49b01f1c85e28 appears to be the correct checksum for v0.0.3

**Comment by russellballestrini** [comment]
Please PR @lazyguru - I'll merge

**Comment by lazyguru** [comment]
Created #24 to fix this

**Comment by russellballestrini** [comment]
@lazyguru thanks for the help!
