### ISSUE TITLE
A silent-fail option would be useful

### ISSUE THREAD

**Issue by fubar** [remind101/ssm-env#25]
I am using SSM parameters to populate environment variables. It's a common pattern for applications to check if an environment variable is present and non-empty before using it, ie. expecting that it may not be set. In that sense it would be useful if ssm-env had a silent-fail option that would resolve a non-existent SSM parameter to an empty value instead of throwing an error.

@russellballestrini what do you think?

**Comment by russellballestrini** [comment]
Could you show an example? I feel like dealing with the error of a non-existent parameter would be done outside the tool but I might not fully understand your usecase.

**Comment by fubar** [comment]
As it is, I don't have the ability to deal with non-existent parameters outside of this tool as this tool throws an error when it encounters one, which is exactly the issue I'm looking to find a more robust solution for.

Presume I have an application that uses a default DB port but allows that to be overwritten via configuration based on environment variables (as is common practice):

```js
const config = {
  dbPort: env.DB_PORT || 1234,
  foo: env.FOO || '',
};
```

Assume I have set up SSM parameter `foo` with value "bar", but parameter `/db/port` has not been created.

```shell
FOO=ssm://foo DB_PORT=ssm:///db/port ssm-env node foo.js
```

This application will fail to start because ssm-env throws an error. This creates undesired coupling between the command and the state of configuration (ie. existence of SSM parameters); or in other words, if I configure an optional config value by creating an SSM parameter, I now also have to modify the command to include that env var/SSM param pair.

What I'm looking for is something like a `--silent-fail` option that would result in:

```
FOO=bar
DB_PORT=
```

Now my application can properly handle configuration with optional values.

**Comment by fubar** [comment]
@russellballestrini any thoughts on this?

**Comment by russellballestrini** [comment]
I'll review a PR, since it is opt-in it shouldn't break existing workflows.

**Comment by russellballestrini** [comment]
https://github.com/remind101/ssm-env/pull/26 I just merged this in, going to close this issue!
