### ISSUE TITLE
Doesn't support IAM roles for service accounts (go sdk upgrade)

### ISSUE THREAD

**Issue by brainflake** [remind101/ssm-env#32]
Hi-

I was setting up [IAM roles for service accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) in my EKS cluster and noticed that this command wasn't able to work with the `AWS_WEB_IDENTITY_TOKEN_FILE` and `AWS_ROLE_ARN` env vars.

I was able to get it working with a newer version of the go sdk (v1.28.8), so it's likely just upgrading that module. Happy to cut a PR if you'd like.

**Comment by russellballestrini** [comment]
@brainflake if your assessment is accurate, this should be fixed in #34 (https://github.com/remind101/ssm-env/blob/master/go.mod#L6-L7)

Thanks to @alexions !
