### ISSUE TITLE
Is this repository supported / maintained?

### ISSUE THREAD

**Issue by spaguette** [remind101/ssm-env#33]
Hi,

We use your library in our company and we lack some features, for example, the support of the versioned format of the SSM parameters. (AWS started to support it 3 years ago with their SSM Go SDK)

We are happy to create a PR to your repo and wanted to know if it's possible for you to check and merge that or it's not maintained anymore.

So the question is:
Is this repo maintained and a PR is possible to be checked out? :)

**Comment by russellballestrini** [comment]
Yes, We still use this tool exclusively at Remind to make secrets management seemless for our 70+ services running with Docker in ECS.

Please create a fork and pull request.

**Comment by alexions** [comment]
Hi @russellballestrini 

That's good :)
Here is the PR that was mentioned: https://github.com/remind101/ssm-env/pull/34

There are 2 major things:
- Migrating to go mod. Go vendoring actually is a nightmare to maintain. Go mod should not brake anything, but will make the project development much much easier.
- Add support of versioned SSM params. Actually, the first point I mentioned is a result of upgrading aws-go-sdk to the latest version (that supports versioning)

**Comment by alexions** [comment]
Actually, I moved my changes to a separate issue:
#35 

I suppose this ticket can be considered as closed?
@spaguette
