### ISSUE TITLE
Add support of versioned SSM params

### ISSUE THREAD

**Issue by alexions** [remind101/ssm-env#35]
There are 2 major things:

- Migrating to go mod. Go vendoring actually is a nightmare to maintain. Go mod should not break anything, but will make the project development much much easier.
- Add support of versioned SSM params. Actually, the first point I mentioned is a result of upgrading aws-go-sdk to the latest version (that supports versioning)

https://github.com/remind101/ssm-env/pull/34

**Comment by russellballestrini** [comment]
Fixed!
