### ISSUE TITLE
Feature: Add include / exclude parameters

### ISSUE THREAD

**Issue by r1b** [remind101/ssm-env#4]
I have many secrets stored in SSM for different applications. Per `least privilege` I do not want an application to have access to more parameters than it needs to function.

**Comment by phobologic** [comment]
Is this necessary, @r1b?  ssm-env only translates existing environment variables that start with `ssm://`.  If you don't want ssm-env to translate a variable, it shouldn't have that variable loaded into it's environment with `ssm://`.  Make sense?
