### ISSUE TITLE
code goes to panic with go1.8.3

### ISSUE THREAD

**Issue by eureka-gh** [remind101/ssm-env#5]
in func (e *expander) expandEnviron(decrypt bool) error {
}

```
input := &ssm.GetParametersInput{
		aws.Bool(decrypt)
	}
```
will trigger panic in my go1.8.3 env.
while 
```
input := &ssm.GetParametersInput{
		WithDecryption: &decrypt,
	}
```
does not.

Besides, line134-136
```
	for k := range names {
		input.Names = append(input.Names, aws.String(k))
	}
```
k is temporary variable, the address will become invalid after for clause.
It's better to append input.Name in for _, envvar := range e.os.Environ()  loop.
```
                if parameter != nil {
			names[*parameter] = true
			ssmVars = append(ssmVars, ssmVar{k, *parameter})
			input.Names = append(input.Names, parameter)
		}
```

**Comment by russellballestrini** [comment]
We now build with `golang:1.11.6` (https://github.com/remind101/ssm-env/blob/master/.circleci/config.yml#L6). Closing this defect report as fixed.
